# Generated by Django 5.2.4 on 2025-07-13 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='screens.screen'),
        ),
    ]
