# Generated by Django 5.2.4 on 2025-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_session_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
    ]
