# Generated by Django 5.2.4 on 2025-07-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rows', models.PositiveSmallIntegerField(help_text='Number of rows (e.g. A–Z → 26 rows)')),
                ('seats_per_row', models.PositiveSmallIntegerField(help_text='Seats in each row (e.g. 20)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(help_text="E.g. 'B-12'; automatically generated by Screen.create_seats()", max_length=5)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screens.screen')),
            ],
            options={
                'ordering': ['screen', 'row', 'number'],
                'unique_together': {('screen', 'label')},
            },
        ),
    ]
